#公共配置
server:
    port: 80
    tomcat:
      uri-encoding: UTF-8
spring:
 #激活哪一个环境的配置文件
  profiles:
    active: dev

  #模板引擎
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
 #热部署
  devtools:
    restart:
      enabled: true
  datasource:
#  连接池配置
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  cache:
    type: redis
#    设置缓存的名称
#    cache-names:
mybatis-plus:
   # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
   # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
   mapper-locations: classpath:/mapper/*Mapper.xml
   #实体扫描，多个package用逗号或者分号分隔
   typeAliasesPackage: com.hhu.mlthfs.plan
   global-config:
     #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
     id-type: 1
     #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
     field-strategy: 2
     #驼峰下划线转换
     db-column-underline: true
     #mp2.3+ 全局表前缀 mp_
     #table-prefix: mp_
     #刷新mapper 调试神器
     refresh-mapper: true
     #数据库大写下划线转换
     capital-mode: true
     # Sequence序列接口实现类配置
     key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
     #逻辑删除配置（下面3个配置）
     logic-delete-value: 1
     logic-not-delete-value: 0
     sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
     #自定义填充策略接口实现
     meta-object-handler: com.hhu.mlthfs.config.SysMetaObjectHandler
   configuration:
     #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
     map-underscore-to-camel-case: true
     cache-enabled: false
     #配置JdbcTypeForNull, oracle数据库必须配置
     jdbc-type-for-null: 'null'


---
#开发环境配置
server:
  #端口
  port: 8087
spring:
  profiles: dev
  #redis配置
  redis:
        database: 0
        host: 192.168.1.102
        port: 6379
        password:      # 密码（默认为空）
        timeout: 6000s # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
        # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
        jedis:
          pool:
            # 最大空闲连接数
            max-idle: 10
            # 最小空闲连接数
            min-idle: 5
            # 等待可用连接的最大时间，负数为不限制
            max-wait:  -1s
            # 最大活跃连接数，负数为不限制
            max-active: -1
  # 数据源Oracle
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.102:1521:mlthfs
    username: hhudba
    password: Jttqbchhu611611
# 日志
logging:
  #配置文件路径
  config: classpath:log/logback.xml
  #日志生成目录
  path: e:/mlthfsLog/

---
#生产环境
server:
  port: 8086
spring:
  profiles: pro

#数据源
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.1.102:1521:mlthfs
      username: hhudba
      password: Jttqbchhu611611

#日志
logging:
  #配置文件路径
  config: classpath:log/logback.xml
  #日志生成目录
  path: e:/mlthfsLog/


---
#测试环境
server:
  port: 8085
spring:
  profiles: test

#数据源
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.1.102:1521:mlthfs
      username: hhudba
      password: Jttqbchhu611611

#日志
logging:
  #配置文件路径
  config: classpath:log/logback.xml
  #日志生成目录
  path: e:/mlthfsLog/
